const FEBBRAIO_DB = {
    "01": ["1958: Viene lanciato l'Explorer 1, il primo satellite USA.", "2003: Disastro dello Space Shuttle Columbia.", "1893: Thomas Edison termina la costruzione del primo studio cinematografico."],
    "02": ["Giorno della Marmotta: Phil deciderà quanto durerà l'inverno.", "1943: Termina la battaglia di Stalingrado, svolta della II Guerra Mondiale.", "1922: Viene pubblicato l'Ulisse di James Joyce."],
    "03": ["1959: 'The Day the Music Died', muore Buddy Holly in un incidente aereo.", "1966: La sonda russa Luna 9 effettua il primo atterraggio morbido sulla Luna.", "1468: Muore Johannes Gutenberg, l'inventore della stampa."],
    "04": ["2004: Mark Zuckerberg lancia Facebook (allora 'TheFacebook').", "1945: Inizia la Conferenza di Jalta con Churchill, Roosevelt e Stalin.", "1902: Nasce Charles Lindbergh, il primo a trasvolare l'Atlantico."],
    "05": ["1919: Charlie Chaplin e altri fondano la United Artists.", "1958: Una bomba all'idrogeno viene persa dalla US Air Force al largo della Georgia (mai ritrovata).", "1997: Le banche svizzere creano un fondo per le vittime dell'Olocausto."],
    "06": ["1952: Elisabetta II diventa Regina del Regno Unito.", "1918: Il Regno Unito concede il voto alle donne sopra i 30 anni.", "1945: Nasce Bob Marley."],
    "07": ["1964: I Beatles arrivano per la prima volta negli Stati Uniti.", "1992: Viene firmato il Trattato di Maastricht, nasce l'Unione Europea.", "1984: Bruce McCandless effettua la prima passeggiata spaziale senza cavo."],
    "08": ["1924: Prima esecuzione della sedia elettrica negli USA (Nevada).", "1828: Nasce Jules Verne, padre della fantascienza.", "1904: Inizia la guerra russo-giapponese."],
    "09": ["1969: Il Boeing 747 compie il suo primo volo.", "1900: Nasce il trofeo di tennis Coppa Davis.", "1943: Termina la battaglia di Guadalcanal."],
    "10": ["1996: Il computer Deep Blue batte per la prima volta Garry Kasparov a scacchi.", "1947: Vengono firmati i Trattati di Parigi dopo la II Guerra Mondiale.", "1923: Muore Wilhelm Röntgen, scopritore dei raggi X."],
    "11": ["1929: Vengono firmati i Patti Lateranensi tra Italia e Santa Sede.", "1990: Nelson Mandela viene rilasciato dopo 27 anni di carcere.", "1847: Nasce Thomas Edison."],
    "12": ["1809: Nascono nello stesso giorno Charles Darwin e Abraham Lincoln.", "1912: L'ultimo imperatore della Cina, Puyi, abdica.", "1999: Il Senato USA assolve Bill Clinton nel caso Lewinsky."],
    "13": ["1945: Inizia il devastante bombardamento di Dresda.", "1633: Galileo Galilei arriva a Roma per il suo processo davanti all'Inquisizione.", "1970: Esce il primo album dei Black Sabbath (nascita dell'Heavy Metal)."],
    "14": ["1946: Viene presentato ENIAC, il primo computer elettronico general purpose.", "1929: Massacro di San Valentino a Chicago (Al Capone).", "2005: Viene attivato il dominio YouTube.com."],
    "15": ["1564: Nasce Galileo Galilei.", "1903: Viene venduto il primo orsetto di peluche (Teddy Bear).", "2013: Un meteore esplode sopra i cieli di Čeljabinsk, in Russia."],
    "16": ["1923: Viene aperta la camera funeraria di Tutankhamon.", "1959: Fidel Castro diventa primo ministro di Cuba.", "1937: Viene brevettato il Nylon."],
    "17": ["1600: Giordano Bruno viene arso sul rogo a Campo de' Fiori.", "1992: Inizia l'inchiesta 'Mani Pulite' in Italia.", "1963: Nasce Michael Jordan."],
    "18": ["1930: L'astronomo Clyde Tombaugh scopre Plutone.", "1564: Muore Michelangelo Buonarroti.", "2021: Il rover Perseverance atterra su Marte."],
    "19": ["1473: Nasce Niccolò Copernico.", "1878: Thomas Edison brevetta il fonografo.", "1985: Viene ritrovata la prima puntata di 'EastEnders' sulla BBC."],
    "20": ["1962: John Glenn è il primo americano nell'orbita terrestre.", "1909: Marinetti pubblica il Manifesto del Futurismo.", "1967: Nasce Kurt Cobain."],
    "21": ["1848: Marx ed Engels pubblicano il Manifesto del Partito Comunista.", "1965: Viene assassinato Malcolm X.", "1953: Watson e Crick scoprono la struttura del DNA."],
    "22": ["1997: Viene annunciata la clonazione della pecora Dolly.", "1732: Nasce George Washington.", "1987: Muore Andy Warhol."],
    "23": ["1455: Data tradizionale di pubblicazione della Bibbia di Gutenberg.", "1903: Cuba affitta la baia di Guantánamo agli Stati Uniti 'in eterno'.", "1954: Prima vaccinazione di massa contro la polio."],
    "24": ["1955: Nasce Steve Jobs.", "2022: Inizia l'invasione russa dell'Ucraina.", "1582: Papa Gregorio XIII annuncia il calendario gregoriano."],
    "25": ["1964: Cassius Clay (Muhammad Ali) diventa campione del mondo pesanti.", "1954: Viene fondata la prima stazione televisiva pubblica in Italia (RAI).", "1986: Marcos fugge dalle Filippine dopo 20 anni di dittatura."],
    "26": ["1991: Tim Berners-Lee presenta il primo browser web.", "1935: Viene effettuata la prima dimostrazione del Radar.", "1815: Napoleone fugge dall'Isola d'Elba."],
    "27": ["1933: Incendio del Reichstag a Berlino.", "1996: Vengono lanciati in Giappone i primi videogiochi dei Pokémon.", "1902: Nasce lo scrittore John Steinbeck."],
    "28": ["1953: Annuncio della scoperta della doppia elica del DNA.", "1986: Viene assassinato il premier svedese Olof Palme.", "2013: Papa Benedetto XVI rinuncia al pontificato."],
    "29": ["1712: In Svezia il 29 febbraio è seguito dal 30 febbraio (caso unico).", "1940: Hattie McDaniel è la prima afroamericana a vincere l'Oscar.", "1996: Fine dell'assedio di Sarajevo."]
};


const MARZO_DB = {
    "01": ["1954: Gli USA testano la bomba all'idrogeno Castle Bravo su Bikini Atoll.", "1896: Henri Becquerel scopre la radioattività.", "1961: J.F. Kennedy fonda i Peace Corps."],
    "02": ["1969: Il Concorde effettua il suo primo volo di prova.", "1972: Viene lanciata la sonda Pioneer 10 verso Giove.", "1836: Il Texas dichiara l'indipendenza dal Messico."],
    "03": ["1847: Nasce Alexander Graham Bell, inventore del telefono.", "1923: Viene pubblicato il primo numero della rivista TIME.", "1931: 'The Star-Spangled Banner' diventa ufficialmente l'inno USA."],
    "04": ["1975: Charlie Chaplin viene nominato Cavaliere dalla Regina Elisabetta II.", "1877: Il balletto 'Il lago dei cigni' debutta al Bolshoi di Mosca.", "1193: Muore Saladino, fondatore della dinastia ayyubide."],
    "05": ["1946: Churchill pronuncia il discorso della 'Cortina di Ferro'.", "1979: La sonda Voyager 1 raggiunge il punto più vicino a Giove.", "1936: Il caccia Spitfire vola per la prima volta."],
    "06": ["1475: Nasce Michelangelo Buonarroti.", "1899: La Bayer registra l'Aspirina come marchio commerciale.", "1937: Nasce Valentina Tereshkova, prima donna nello spazio."],
    "07": ["1876: Alexander Graham Bell riceve il brevetto per il telefono.", "1917: Viene registrato il primo disco Jazz della storia.", "161 fine dell'era di Antonino Pio, Marco Aurelio diventa imperatore."],
    "08": ["1908: Inizia lo sciopero delle operaie tessili di New York (origine Festa della Donna).", "1917: Inizia la Rivoluzione di Febbraio in Russia.", "1817: Viene fondata la borsa di New York (NYSE)."],
    "09": ["1959: La bambola Barbie viene presentata alla fiera del giocattolo di New York.", "1934: Nasce Yuri Gagarin, primo uomo nello spazio.", "1964: La prima Ford Mustang esce dalla catena di montaggio."],
    "10": ["1876: Prima telefonata della storia: 'Mr. Watson, come here, I want to see you'.", "1977: Vengono scoperti gli anelli di Urano.", "1940: Muore Mikhail Bulgakov, autore de 'Il Maestro e Margherita'."],
    "11": ["2011: Disastro nucleare di Fukushima dopo un violento terremoto e tsunami.", "1918: Primo caso registrato di 'Influenza Spagnola' negli USA.", "1818: Viene pubblicato 'Frankenstein' di Mary Shelley."],
    "12": ["1989: Tim Berners-Lee presenta la proposta per il World Wide Web.", "1930: Gandhi inizia la 'Marcia del Sale' per l'indipendenza indiana.", "1947: Viene enunciata la Dottrina Truman."],
    "13": ["1781: William Herschel scopre il pianeta Urano.", "1930: Viene annunciata la scoperta di Plutone (avvenuta a febbraio).", "1997: Luci di Phoenix: migliaia di persone avvistano strani oggetti nel cielo."],
    "14": ["1879: Nasce Albert Einstein.", "Pi Day: Si festeggia la costante matematica π (3.14).", "1932: George Eastman, fondatore di Kodak, muore suicida."],
    "15": ["Idi di Marzo (44 a.C.): Assassinio di Giulio Cesare.", "1906: Viene fondata la Rolls-Royce.", "1972: Esce nelle sale americane 'Il Padrino'."],
    "16": ["1926: Robert Goddard lancia il primo razzo a propellente liquido.", "1978: Rapimento di Aldo Moro e uccisione della sua scorta.", "1966: La missione Gemini 8 effettua il primo aggancio nello spazio."],
    "17": ["1861: Viene proclamato il Regno d'Italia.", "San Patrizio: Festa nazionale irlandese.", "1958: Viene lanciato il Vanguard 1, il più vecchio satellite ancora in orbita."],
    "18": ["1965: Aleksej Leonov compie la prima passeggiata spaziale della storia.", "1314: Jacques de Molay, ultimo Gran Maestro dei Templari, viene arso vivo.", "1931: Nasce l'inventore del mouse, Douglas Engelbart."],
    "19": ["1932: Viene inaugurato il Sydney Harbour Bridge.", "1915: Plutone viene fotografato per la prima volta (ma non riconosciuto).", "1982: Nasce l'album 'The Number of the Beast' degli Iron Maiden."],
    "20": ["1916: Albert Einstein pubblica la Teoria della Relatività Generale.", "1969: John Lennon e Yoko Ono si sposano a Gibilterra.", "1995: Attacco al gas Sarin nella metropolitana di Tokyo."],
    "21": ["1963: Chiude definitivamente il carcere di Alcatraz.", "2006: Jack Dorsey pubblica il primo Tweet della storia.", "1685: Nasce Johann Sebastian Bach."],
    "22": ["1895: Prima proiezione cinematografica privata dei fratelli Lumière.", "1997: La cometa Hale-Bopp raggiunge il punto più vicino alla Terra.", "1963: Esce 'Please Please Me', il primo album dei Beatles."],
    "23": ["1839: Primo utilizzo documentato del termine 'OK' sul Boston Morning Post.", "1956: Il Pakistan diventa la prima repubblica islamica del mondo.", "2001: La stazione spaziale Mir viene fatta precipitare nell'Oceano Pacifico."],
    "24": ["1882: Robert Koch annuncia la scoperta del batterio della tubercolosi.", "1989: Il naufragio della Exxon Valdez causa un disastro ambientale in Alaska.", "2001: Apple rilascia Mac OS X Cheetah."],
    "25": ["1957: Vengono firmati i Trattati di Roma (nascita della CEE).", "1655: Christiaan Huygens scopre Titano, la luna di Saturno.", "1941: Il Regno di Jugoslavia aderisce al Patto Tripartito."],
    "26": ["1953: Jonas Salk annuncia il vaccino contro la poliomielite.", "1979: Egitto e Israele firmano il trattato di pace a Washington.", "1997: Vengono ritrovati i corpi del suicidio di massa della setta Heaven's Gate."],
    "27": ["1977: Disastro aereo di Tenerife: scontro tra due Boeing 747 (583 vittime).", "1998: La FDA approva il Viagra.", "1914: Avviene la prima trasfusione di sangue conservato."],
    "28": ["1939: Fine della Guerra Civile Spagnola con la caduta di Madrid.", "1979: Incidente alla centrale nucleare di Three Mile Island (USA).", "1930: Costantinopoli e Angora cambiano nome in Istanbul e Ankara."],
    "29": ["1974: La sonda Mariner 10 è la prima a sorvolare Mercurio.", "1886: John Pemberton produce la prima caraffa di Coca-Cola.", "1971: Charles Manson viene condannato alla pena di morte (poi commutata)."],
    "30": ["1853: Nasce Vincent van Gogh.", "1867: Gli USA acquistano l'Alaska dalla Russia per 7,2 milioni di dollari.", "1981: Tentato assassinio di Ronald Reagan."],
    "31": ["1889: Viene inaugurata la Torre Eiffel a Parigi.", "1999: Esce nei cinema il film 'Matrix'.", "1732: Nasce Franz Joseph Haydn."]
};